{{- if and (not .Values.cloudscaleAPI.token) (not .Values.cloudscaleAPI.existingSecret) }}
{{ fail "either cloudscaleAPI.token or cloudscaleAPI.existingSecret must be set" }}
{{- end }}
{{- if and .Values.cloudscaleAPI.token (not .Values.cloudscaleAPI.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "autoscaler-cloudscale.fullname" . }}-api
  labels:
    {{- include "autoscaler-cloudscale.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ .Values.cloudscaleAPI.token | quote }}
{{- end }}
